version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        DEVELOPMENT: "false"
    ports:
      - 80:80
    environment:
      DEVELOPMENT: "false"